# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0003_auto_20160629_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('role', models.BooleanField()),
            ],
        ),
    ]
